### ISSUE TITLE
Does it work on MacOS?

### ISSUE THREAD

**Issue by cgfarmer4** [hellojoelhuber/swiftui-drag-and-drop#4]
Looking for something simple on MacOS outside of using dropdelegates

**Comment by hellojoelhuber** [comment]
Hi, I haven't tested this library on macOS yet, but it is [packaged for macOS](https://github.com/hellojoelhuber/swiftui-drag-and-drop/blob/main/Package.swift#L8). If you try it and run into issues, please report and I'd be happy to patch them!

**Comment by cgfarmer4** [comment]
Ooh thanks for pointer! ❤️ ill give it a whirl and reopen if not.

**Comment by sailajakolusu** [comment]
Hi Joel, Hope you are doing good,  i want this card code in  storyboards instead of swift UI i am new to ios please can you hepl me.. I  have one task that is example if i have 12345  cards i have selected card 4 if drag  and placed in b/w 1 and 2 cards , selected card should come one top of half 1 and below 2.
